name: "🐞 Reporte de Error"
description: "Reporta un error para ayudarnos a mejorar."
title: "🐞 Reporte de Error: ..."
labels: ["error"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo de completar nuestro formulario! 🙏

  - type: textarea
    id: pasos_reproduccion
    attributes:
      label: "📝 ¿Cómo Reproducir el Error?"
      description: "Cuéntanos paso a paso qué hiciste cuando apareció el problema."
      placeholder: "1. Entré a la página...\n2. Hice clic en...\n3. Entonces aparece..."
    validations:
      required: true

  - type: textarea
    id: comportamiento_esperado
    attributes:
      label: "👍 ¿Qué Debería Pasar?"
      description: "¿Cuál era el resultado que esperabas?"
      placeholder: "Esperaba que..."
    validations:
      required: true

  - type: textarea
    id: comportamiento_actual
    attributes:
      label: "👎 ¿Qué Pasó en Realidad?"
      description: "Describe qué es lo que está fallando. Puedes agregar capturas de pantalla."
      placeholder: "En lugar de eso, lo que pasó fue..."
    validations:
      required: true

  - type: dropdown
    id: navegadores
    attributes:
      label: "🌐 ¿En qué navegadores estás viendo el problema?"
      multiple: true
      options:
        - "Firefox"
        - "Chrome"
        - "Safari"
        - "Otro"

  - type: checkboxes
    id: reportes_similares
    attributes:
      label: "¿Has Verificado Reportes Similares?"
      description: "Asegúrate de que este problema no haya sido reportado previamente buscando en nuestra lista de issues."
      options:
        - label: "Sí, he verificado reportes similares y este es único."
          required: true

  - type: checkboxes
    id: codigo_conducta
    attributes:
      label: "¿Has Leído Nuestro Código de Conducta?"
      description: "Por favor confirma que has leído y entendido nuestro [Código de Conducta](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: "Sí, he leído y acepto el Código de Conducta."
          required: true
