name: "♻️ Solicitud de Funcionalidad"
description: "Sugiere una nueva funcionalidad o mejora para nuestro proyecto."
title: "♻️ Solicitud de Funcionalidad: ..."
labels: ["funcionalidad"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tomarte el tiempo de completar nuestro formulario! 🙏

  - type: textarea
    id: contexto
    attributes:
      label: "📅 Contexto"
      description: "Explica la motivación detrás de esta solicitud. Describe por qué sería útil o qué necesidad satisfaría."
      placeholder: "Sería útil si [...]"
    validations:
      required: true

  - type: textarea
    id: solucion
    attributes:
      label: "🎯 Describe la Solución que Te Gustaría"
      description: "Describe claramente lo que te gustaría que pasara, detallando cualquier funcionalidad nueva o cambios."
      placeholder: "Describe el resultado o comportamiento deseado."
    validations:
      required: true

  - type: textarea
    id: contexto_adicional
    attributes:
      label: "📷 Contexto Adicional"
      description: "Incluye cualquier otra información relevante, capturas de pantalla o ejemplos que nos ayuden a entender mejor tu solicitud."
      placeholder: "Proporciona detalles extra si están disponibles."
    validations:
      required: false

  - type: checkboxes
    id: solicitudes_similares
    attributes:
      label: "¿Has Verificado Solicitudes Similares?"
      description: "Asegúrate de que esta solicitud no haya sido discutida previamente buscando en nuestra lista de issues."
      options:
        - label: "Sí, he verificado solicitudes similares y esta es única."
          required: true

  - type: checkboxes
    id: codigo_conducta
    attributes:
      label: "¿Has Leído Nuestro Código de Conducta?"
      description: "Por favor confirma que has leído y entendido nuestro [Código de Conducta](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: "Sí, he leído y acepto el Código de Conducta."
          required: true
