name: "🌱 Reportar Nuevo Punto de Reciclaje"
description: "Agregar un nuevo centro de reciclaje a nuestro directorio."
title: "🌱 Nuevo Punto: [Nombre del Punto]"
labels: ["nuevo-punto", "punto-reciclaje"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        
        **Antes de continuar, por favor verifica que este punto NO esté ya registrado en nuestra plataforma.**

        La forma más fácil de verificar esto es:
        1. Usa los filtros por **ubicación** y **material** para reducir los resultados
        2. Revisa si tu punto ya aparece en la lista

        📝 **¿Necesitas actualizar información de un punto existente?** 
        Usa este formulario: [Actualizar Centro de Reciclaje](https://github.com/Aqui-Reciclo-Panama/.github/issues/new?template=update-center.yml)

        ---

  - type: dropdown
    id: fuente_informacion
    attributes:
      label: "🔍 ¿Cómo obtuviste esta información?"
      options:
        - ""
        - "Trabajo/soy dueño del punto de reciclaje"
        - "Visité el punto personalmente"
        - "Lo vi en redes sociales/internet"
        - "Otro"
    validations:
      required: true
      
  - type: input
    id: entidad_empresa
    attributes:
      label: "🏢 Empresa u Organización"
      description: "¿Quién opera este punto de reciclaje?"
    validations:
      required: true

  - type: textarea
    id: direccion
    attributes:
      label: "🏠 Dirección Completa"
      description: "Incluye puntos de referencia para facilitar la ubicación"
    validations:
      required: true

  - type: input
    id: google_maps
    attributes:
      label: "🗺️ Enlace de Google Maps"
      description: "Copia y pega el enlace de Google Maps de la ubicación exacta"
      placeholder: "https://maps.google.com/..."
    validations:
      required: true

  - type: input
    id: contacto
    attributes:
      label: "📞 Teléfono o Email del Punto"
      description: "Número de contacto o email del centro"
      placeholder: "+507 123-4567 / punto123@mail.com"
    validations:
      required: false

  - type: textarea
    id: horarios
    attributes:
      label: "🕐 Horarios de Atención"
      placeholder: "Ej: Lun-Vie: 8AM-5PM, Sáb: 8AM-12PM, Dom: Cerrado"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## ♻️ Materiales que Acepta
        **Selecciona SOLO los materiales que sepas con certeza que acepta este punto**

  - type: checkboxes
    id: materiales_no_peligrosos
    attributes:
      label: "♻️ Materiales No Peligrosos"
      options:
        - label: "Papel"
        - label: "Plástico"
        - label: "Cartón"
        - label: "Botellas de Amor"
        - label: "EcoBricks"
        - label: "Aluminio"
        - label: "Metales"
        - label: "TetraPak"
        - label: "Vidrio"
        - label: "Madera"
        - label: "Llantas de caucho"
        - label: "Residuos orgánicos"
        - label: "Residuos de construcción"
        - label: "Textiles"
        - label: "Residuos voluminosos"
        - label: "Aceite"
    validations:
      required: true

  - type: checkboxes
    id: materiales_peligrosos
    attributes:
      label: "⚠️ Materiales Peligrosos"
      description: "Solo selecciona si estás seguro que los acepta"
      options:
        - label: "Baterías"
        - label: "Envases peligrosos"

  - type: checkboxes
    id: raee
    attributes:
      label: "🔌 RAEE (Residuos de Aparatos Eléctricos y Electrónicos)"
      description: "Solo selecciona si estás seguro que los acepta"
      options:
        - label: "Equipos pequeños"
        - label: "Equipos grandes"
        - label: "Equipos con pantallas"
        - label: "Paneles fotovoltaicos"
        - label: "Lámparas y bombillas"

  - type: textarea
    id: informacion_adicional
    attributes:
      label: "📝 Información Extra"
      description: "Cualquier detalle importante (opcional)"
    validations:
      required: false

  - type: input
    id: fecha_visita
    attributes:
      label: "📅 ¿Cuándo verificaste esta información?"
      placeholder: "Ej: Enero 2025, Esta semana"
    validations:
      required: false

  - type: checkboxes
    id: verificacion
    attributes:
      label: "✅ Confirmación Final"
      options:
        - label: "Confirmé que este punto NO está registrado"
          required: true
        - label: "La información que proporciono es precisa según mi conocimiento"
          required: true
