name: "🌱 Reportar Nuevo Punto de Reciclaje"
description: "Agregar un nuevo centro de reciclaje a nuestro directorio."
title: "🌱 Nuevo Punto: [Nombre del Punto]"
labels: ["nuevo-punto", "punto-reciclaje"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🌱 ¡Gracias por reportar un nuevo punto de reciclaje!

        **Antes de continuar, por favor verifica que este punto NO esté ya registrado en nuestra plataforma.**

        La forma más fácil de verificar esto es:
        1. Usa los filtros por **ubicación** y **material** para reducir los resultados
        32 Revisa si tu punto ya aparece en la lista

        📝 **¿Necesitas actualizar información de un punto existente?** 
        Usa este formulario: [Actualizar Centro de Reciclaje](https://github.com/Aqui-Reciclo-Panama/.github/issues/new?template=update-center.yml)

        ---

  - type: dropdown
    id: fuente_informacion
    attributes:
      label: "🔍 ¿Cómo obtuviste esta información?"
      options:
        - ""
        - "Trabajo/soy dueño del punto de reciclaje"
        - "Visité el punto personalmente"
        - "Lo vi en redes sociales/internet"
        - "Otro"
    validations:
      required: true

  - type: input
    id: nombre_punto
    attributes:
      label: "📍 Nombre del Punto de Reciclaje"
      description: "Nombre completo del centro o punto limpio"
    validations:
      required: true

  - type: input
    id: entidad_empresa
    attributes:
      label: "🏢 Empresa u Organización"
      description: "¿Quién opera este punto de reciclaje?"
    validations:
      required: true

  - type: dropdown
    id: provincia
    attributes:
      label: "🗺️ Provincia"
      options:
        - ""
        - "Bocas del Toro"
        - "Chiriquí"
        - "Coclé"
        - "Colón"
        - "Darién"
        - "Herrera"
        - "Los Santos"
        - "Panamá"
        - "Panamá Oeste"
        - "Veraguas"
        - "Guna Yala"
        - "Emberá-Wounaan"
        - "Ngäbe-Buglé"
    validations:
      required: true

  - type: textarea
    id: direccion
    attributes:
      label: "🏠 Dirección Completa"
      description: "Incluye puntos de referencia para facilitar la ubicación"
      placeholder: "Ej: Calle 50, Edificio Torre Global, Planta Baja, frente al Metro Mall"
    validations:
      required: true

  - type: input
    id: google_maps
    attributes:
      label: "🗺️ Enlace de Google Maps"
      description: "Copia y pega el enlace de Google Maps de la ubicación exacta"
      placeholder: "https://maps.google.com/..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 📞 Contacto e Información Básica

  - type: input
    id: telefono
    attributes:
      label: "📞 Teléfono del Punto"
      description: "Número de contacto del centro (no tu número personal)"
      placeholder: "+507 123-4567"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: "📧 Email del Punto"
      description: "Correo del centro (no tu email personal)"
      placeholder: "info@reciclaje.com"
    validations:
      required: false

  - type: dropdown
    id: incentivos
    attributes:
      label: "💰 ¿Ofrece Incentivos?"
      description: "¿Dan descuentos, puntos, dinero o algún beneficio por reciclar?"
      options:
        - ""
        - "Sí"
        - "No"
        - "No lo sé"
    validations:
      required: true

  - type: textarea
    id: describir_incentivos
    attributes:
      label: "🎁 ¿Qué Incentivos Ofrece?"
      description: "Solo completa si seleccionaste 'Sí' arriba"
      placeholder: "Ej: B/. 0.10 por libra de plástico, descuentos en compras, puntos canjeables"
    validations:
      required: false

  - type: textarea
    id: horarios
    attributes:
      label: "🕐 Horarios de Atención"
      placeholder: "Ej: Lun-Vie: 8AM-5PM, Sáb: 8AM-12PM, Dom: Cerrado"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## ♻️ Materiales que Acepta
        **Selecciona SOLO los materiales que sepas con certeza que acepta este punto**

  - type: checkboxes
    id: materiales_no_peligrosos
    attributes:
      label: "♻️ Materiales No Peligrosos"
      options:
        - label: "Periódicos"
        - label: "Directorios / Guías Telefónicas"
        - label: "Revistas"
        - label: "Papel Blanco (bond)"
        - label: "Papel de Color"
        - label: "Papel Mixto, Caribe, Mezclado"
        - label: "Plástico 1 (PET)"
        - label: "Plástico 2 (HDPE)"
        - label: "Plástico 5 (PP)"
        - label: "5 Polipropileno (PP)"
        - label: "Plástico 3 (PVC)"
        - label: "Plástico 6 (PS)"
        - label: "Cartón"
        - label: "Botellas de Amor"
        - label: "EcoBricks"
        - label: "Latas"
        - label: "Hojalata (latas de conserva)"
        - label: "Hierro"
        - label: "Bronce"
        - label: "Cobre"
        - label: "Acero inoxidable"
        - label: "Chatarra"
        - label: "TetraPak"
        - label: "Vidrio Verde"
        - label: "Vidrio Ámbar/Chocolate"
        - label: "Vidrio Transparente"
        - label: "Vidrio Plano"
        - label: "Espejos"
        - label: "Pallets de Madera"
        - label: "Llantas de caucho"
        - label: "Residuos orgánicos"
        - label: "Residuos de construcción y demolición"
        - label: "Textiles"
        - label: "Residuos voluminosos"
    validations:
      required: true

  - type: checkboxes
    id: materiales_peligrosos
    attributes:
      label: "⚠️ Materiales Peligrosos"
      description: "Solo selecciona si estás seguro que los acepta"
      options:
        - label: "Aceite de cocina"
        - label: "Aceite de motor"
        - label: "Envases de plaguicidas"
        - label: "Cartuchos de tintas y tóner"
        - label: "Envases de aerosoles"
        - label: "Baterías alcalinas"
        - label: "Baterías de litio"
        - label: "Baterías de ácido de gel"
        - label: "Baterías de ácido en líquido"

  - type: checkboxes
    id: raee
    attributes:
      label: "🔌 RAEE (Residuos de Aparatos Eléctricos y Electrónicos)"
      description: "Solo selecciona si estás seguro que los acepta"
      options:
        - label: "Lámparas y bombillas"
        - label: "Paneles fotovoltaicos"
        - label: "Monitores de pantalla plana y similares"
        - label: "Monitores con tubos de rayos catódicos"
        - label: "Televisores"
        - label: "Lavadoras"
        - label: "Calentadores"
        - label: "Bicicletas eléctricas"
        - label: "Copiadoras"
        - label: "Aparatos médicos y de laboratorio (grandes)"
        - label: "Contadores"
        - label: "Celulares"
        - label: "Tablets"
        - label: "Computadoras"
        - label: "Impresoras"
        - label: "Microondas"
        - label: "Consolas de juego"
        - label: "Aires acondicionados"
        - label: "Refrigeradores"
        - label: "Compresores"
        - label: "Congeladores"
        - label: "Radiadores"

  - type: textarea
    id: informacion_adicional
    attributes:
      label: "📝 Información Extra"
      description: "Cualquier detalle importante (opcional)"
      placeholder: "Ej: Solo atienden empresas, requieren cita previa, acceso para discapacitados"
    validations:
      required: false

  - type: input
    id: fecha_visita
    attributes:
      label: "📅 ¿Cuándo verificaste esta información?"
      placeholder: "Ej: Enero 2025, Esta semana"
    validations:
      required: false

  - type: checkboxes
    id: verificacion
    attributes:
      label: "✅ Confirmación Final"
      options:
        - label: "Confirmé que este punto NO está registrado"
          required: true
        - label: "La información que proporciono es precisa según mi conocimiento"
          required: true
