name: "🆕 Nuevo Punto de Reciclaje"
description: "Reportar un nuevo punto de reciclaje que no está en nuestro directorio."
title: "🆕 Nuevo Punto: [Nombre del Punto]"
labels: ["nuevo-punto", "punto-reciclaje"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por ayudarnos a expandir nuestra red de reciclaje! 🌱

        Estás reportando un **nuevo punto de reciclaje** que no está en nuestro directorio.
        Por favor proporciona la mayor cantidad de detalles posibles.

        ---

        **¿Te equivocaste de plantilla?** 🤔

        Si quieres **actualizar un punto** que ya existe en nuestro directorio, usa esta plantilla:
        📝 **[Actualizar Punto Existente](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/.github/ISSUE_TEMPLATE/update-center.yml)**

  - type: dropdown
    id: fuente_informacion
    attributes:
      label: "🔍 Fuente de Información"
      description: "¿Cómo obtuviste esta información?"
      options:
        - "Trabajo/soy dueño del punto de reciclaje"
        - "Visité el punto personalmente"
        - "Lo vi en redes sociales/internet"
        - "Otro"
    validations:
      required: true

  - type: input
    id: nombre_punto
    attributes:
      label: "📍 Nombre del Punto Limpio"
      description: "Nombre del centro de reciclaje o punto limpio"
      placeholder: "Centro de Reciclaje Verde"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 📄 ¿Eres dueño u operador del punto?
        Si eres dueño u operador del punto de reciclaje, puedes:
        1. **[Descargar nuestra plantilla Excel](https://raw.githubusercontent.com/Aqui-Reciclo-Panama/.github/main/templates/template-recycling-center.xlsx)** 📥
        2. Completar todos los campos
        3. Subirla aquí abajo

        Esto nos ayudará a procesar tu información más rápidamente.

  - type: textarea
    id: plantilla_completa
    attributes:
      label: "📎 Plantilla Completa (Arrastra y suelta el archivo aquí)"
      description: "Si completaste nuestra plantilla Excel/PDF, pega aquí el contenido"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        💡 **Tip:** Si no eres dueño del punto, puedes llenar la información que tengas disponible en las siguientes secciones.

        ---
        ## 📋 Información Básica del Punto

  - type: input
    id: entidad_empresa
    attributes:
      label: "🏢 Entidad/Empresa"
      description: "Organización o empresa que opera el punto de reciclaje"
      placeholder: "Empresa ABC"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 📍 Ubicación

  - type: dropdown
    id: provincia
    attributes:
      label: "🗺️ Provincia"
      description: "Selecciona la provincia donde se encuentra el punto de reciclaje"
      options:
        - ""
        - "Bocas del Toro"
        - "Chiriquí"
        - "Coclé"
        - "Colón"
        - "Darién"
        - "Herrera"
        - "Los Santos"
        - "Panamá"
        - "Panamá Oeste"
        - "Veraguas"
        - "Guna Yala"
        - "Emberá-Wounaan"
        - "Ngäbe-Buglé"
    validations:
      required: true

  - type: input
    id: distrito
    attributes:
      label: "🏘️ Distrito"
      description: "Distrito donde se encuentra el punto de reciclaje"
      placeholder: "Distrito ABC"
    validations:
      required: true

  - type: input
    id: corregimiento
    attributes:
      label: "📍 Corregimiento"
      description: "Corregimiento donde se encuentra el punto de reciclaje"
      placeholder: "Corregimiento ABC"
    validations:
      required: false

  - type: textarea
    id: direccion
    attributes:
      label: "🏠 Dirección Exacta"
      description: "Dirección completa del punto de reciclaje"
      placeholder: "Calle 123, Edificio ABC, Planta Baja"
    validations:
      required: true

  - type: input
    id: google_maps
    attributes:
      label: "🗺️ Enlace de Google Maps"
      description: "Enlace de Google Maps donde se encuentra el punto de reciclaje"
      placeholder: "https://maps.google.com/..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 📞 Información de Contacto

  - type: input
    id: telefono
    attributes:
      label: "📞 Teléfono de Contacto del Punto"
      description: "Número de teléfono del punto de reciclaje (no tu número personal)"
      placeholder: "+507 123-4567"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: "📧 Email de Contacto del Punto"
      description: "Dirección de correo electrónico del punto de reciclaje (no tu email personal)"
      placeholder: "info@reciclaje.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 💰 Incentivos y Horarios

  - type: dropdown
    id: incentivos
    attributes:
      label: "💰 ¿Ofrece Incentivos?"
      description: "¿El punto de reciclaje ofrece incentivos?"
      options:
        - ""
        - "Sí"
        - "No"
        - "No lo sé"
    validations:
      required: false

  - type: textarea
    id: describir_incentivos
    attributes:
      label: "🎁 Describir Incentivos"
      description: "Si ofrece incentivos, describe cuáles son"
      placeholder: "Descuentos, puntos, dinero en efectivo, etc."
    validations:
      required: false

  - type: textarea
    id: horarios
    attributes:
      label: "🕐 Horarios de Atención"
      description: "Horarios de atención del punto de reciclaje"
      placeholder: "Lunes a viernes: 8:00 AM - 5:00 PM\nSábados: 8:00 AM - 12:00 PM\nDomingos: Cerrado"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## ♻️ Materiales que Acepta

  - type: checkboxes
    id: materiales_no_peligrosos
    attributes:
      label: "♻️ Materiales No Peligrosos"
      description: "Selecciona todos los materiales no peligrosos que acepta"
      options:
        - label: "Periódicos"
        - label: "Directorios / Guías Telefónicas"
        - label: "Revistas"
        - label: "Papel Blanco (bond)"
        - label: "Papel de Color"
        - label: "Papel Mixto, Caribe, Mezclado"
        - label: "Plástico 1 (PET)"
        - label: "Plástico 2 (HDPE)"
        - label: "Plástico 5 (PP)"
        - label: "5 Polipropileno (PP)"
        - label: "Plástico 3 (PVC)"
        - label: "Plástico 6 (PS)"
        - label: "Cartón"
        - label: "Botellas de Amor"
        - label: "EcoBricks"
        - label: "Latas"
        - label: "Hojalata (latas de conserva)"
        - label: "Hierro"
        - label: "Bronce"
        - label: "Cobre"
        - label: "Acero inoxidable"
        - label: "Chatarra"
        - label: "TetraPak"
        - label: "Vidrio Verde"
        - label: "Vidrio Ámbar/Chocolate"
        - label: "Vidrio Transparente"
        - label: "Vidrio Plano"
        - label: "Espejos"
        - label: "Pallets de Madera"
        - label: "Llantas de caucho"
        - label: "Residuos orgánicos"
        - label: "Residuos de construcción y demolición"
        - label: "Textiles"
        - label: "Residuos voluminosos"

  - type: checkboxes
    id: materiales_peligrosos
    attributes:
      label: "⚠️ Materiales Peligrosos"
      description: "Selecciona todos los materiales peligrosos que acepta"
      options:
        - label: "Aceite de cocina"
        - label: "Aceite de motor"
        - label: "Envases de plaguicidas"
        - label: "Cartuchos de tintas y tóner"
        - label: "Envases de aerosoles"
        - label: "Baterías alcalinas"
        - label: "Baterías de litio"
        - label: "Baterías de ácido de gel"
        - label: "Baterías de ácido en líquido"

  - type: checkboxes
    id: raee
    attributes:
      label: "🔌 RAEE (Residuos de Aparatos Eléctricos y Electrónicos)"
      description: "Selecciona todos los residuos electrónicos que acepta"
      options:
        - label: "Lámparas y bombillas"
        - label: "Paneles fotovoltaicos"
        - label: "Monitores de pantalla plana y similares"
        - label: "Monitores con tubos de rayos catódicos"
        - label: "Televisores"
        - label: "Lavadoras"
        - label: "Calentadores"
        - label: "Bicicletas eléctricas"
        - label: "Copiadoras"
        - label: "Aparatos médicos y de laboratorio (grandes)"
        - label: "Contadores"
        - label: "Celulares"
        - label: "Tablets"
        - label: "Computadoras"
        - label: "Impresoras"
        - label: "Microondas"
        - label: "Consolas de juego"
        - label: "Aires acondicionados"
        - label: "Refrigeradores"
        - label: "Compresores"
        - label: "Congeladores"
        - label: "Radiadores"

  - type: markdown
    attributes:
      value: |
        ---
        ## 📝 Información Adicional

  - type: textarea
    id: informacion_adicional
    attributes:
      label: "📋 Información Adicional"
      description: "Cualquier información adicional que consideres relevante"
      placeholder: "Requisitos especiales, accesibilidad, características notables, etc."
    validations:
      required: false

  - type: input
    id: fecha_visita
    attributes:
      label: "📅 Fecha de Visita"
      description: "¿Cuándo visitaste o verificaste esta información?"
      placeholder: "Enero 2025"
    validations:
      required: false

  - type: checkboxes
    id: verificacion
    attributes:
      label: "✅ Verificación"
      description: "Por favor confirma lo siguiente"
      options:
        - label: "He verificado que esta información es precisa según mi conocimiento."
          required: true
        - label: "Tengo permiso para compartir esta información públicamente."
          required: true
        - label: "Confirmo que este es un NUEVO punto que no está en el directorio actual."
          required: true

  - type: checkboxes
    id: codigo_conducta
    attributes:
      label: "¿Has Leído Nuestro Código de Conducta?"
      description: "Por favor confirma que has leído y entendido nuestro [Código de Conducta](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: "Sí, he leído y acepto el Código de Conducta."
          required: true
