name: "🔄 Actualizar Punto Existente"
description: "Actualizar información de un punto de reciclaje que ya está en nuestro directorio."
title: "🔄 Actualizar: [Nombre Exacto del Punto]"
labels: ["actualizar-punto", "punto-reciclaje"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por ayudarnos a mantener actualizada nuestra red de reciclaje! 🌱

        Estás reportando **cambios en un punto existente** de nuestro directorio.

        **⚠️ IMPORTANTE:** Para actualizar un punto existente, debes usar el nombre EXACTO como aparece en nuestro directorio de puntos de reciclaje.

        ---

        **¿Te equivocaste de plantilla?** 🤔

        Si quieres **agregar un punto nuevo** que no existe en nuestro directorio, usa esta plantilla:
        📝 **[Crear Nuevo Punto de Reciclaje](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/.github/ISSUE_TEMPLATE/new-center.yml)**

  - type: dropdown
    id: fuente_informacion
    attributes:
      label: "🔍 Fuente de Información"
      description: "¿Cómo obtuviste esta información?"
      options:
        - "Trabajo/soy dueño del punto de reciclaje"
        - "Visité el punto personalmente"
        - "Lo vi en redes sociales/internet"
        - "Otro"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📍 Identificación del Punto

  - type: input
    id: nombre_punto_exacto
    attributes:
      label: "📍 Nombre EXACTO del Punto a Actualizar"
      description: "⚠️: Debe ser el nombre exacto como aparece en nuestro directorio. Si no coincide exactamente, no podremos procesar la actualización."
      placeholder: "Escriba el nombre exacto como aparece en el directorio"
    validations:
      required: true

  - type: textarea
    id: ubicacion_confirmacion
    attributes:
      label: "🗺️ Ubicación del Punto (para confirmación)"
      description: "Ayúdanos a confirmar que es el punto correcto: provincia, distrito, dirección aproximada"
      placeholder: "Provincia: Panamá\nDistrito: Panamá\nDirección: Calle 50, cerca del Metro..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🔍 ¿Qué ha cambiado?

  - type: checkboxes
    id: que_cambio
    attributes:
      label: "🔍 Cambios a Reportar"
      description: "Selecciona todos los cambios que quieres reportar"
      options:
        - label: "Horarios de atención"
        - label: "El punto ya no existe / cerró permanentemente"
        - label: "Ahora recicla materiales adicionales"
        - label: "Ya no recicla algunos materiales que tenían listados"
        - label: "Cambio de información de contacto (teléfono, email)"
        - label: "Cambio en incentivos ofrecidos"
        - label: "Otro cambio"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 📝 Detalles de los Cambios
        *Completa solo las secciones relevantes según lo que seleccionaste arriba*

  - type: textarea
    id: detalle_horarios
    attributes:
      label: "🕐 Nuevos Horarios de Atención"
      description: "Si seleccionaste cambio de horarios, proporciona los nuevos horarios"
      placeholder: "Lunes a Viernes: 9:00 AM - 4:00 PM\nSábados: 8:00 AM - 12:00 PM\nDomingos: Cerrado"
    validations:
      required: false

  - type: textarea
    id: detalle_cierre_permanente
    attributes:
      label: "🚫 Detalles del Cierre Permanente"
      description: "Si el punto cerró permanentemente, proporciona detalles (cuándo, por qué)"
      placeholder: "Cerró hace 1 mes. El local está vacío y hay un letrero que dice 'Se alquila'..."
    validations:
      required: false

  - type: textarea
    id: detalle_cierre_temporal
    attributes:
      label: "⏸️ Detalles del Cierre Temporal"
      description: "Si el punto cerró temporalmente, proporciona detalles (cuándo, por qué, cuándo reabre)"
      placeholder: "Cerrado desde enero 2025 por renovaciones. Reabren en marzo 2025..."
    validations:
      required: false

  - type: textarea
    id: detalle_materiales_nuevos
    attributes:
      label: "➕ Materiales Nuevos que Acepta"
      description: "Si ahora recicla materiales adicionales, especifica cuáles"
      placeholder: "Ahora también acepta: pilas, aceite de cocina usado..."
    validations:
      required: false

  - type: textarea
    id: detalle_materiales_removidos
    attributes:
      label: "➖ Materiales que Ya No Acepta"
      description: "Si ya no recicla algunos materiales, especifica cuáles"
      placeholder: "Ya no acepta: vidrio, textiles..."
    validations:
      required: false

  - type: textarea
    id: detalle_contacto
    attributes:
      label: "📞 Nueva Información de Contacto"
      description: "Si cambió el teléfono o email, proporciona la nueva información"
      placeholder: "Nuevo teléfono: +507 987-6543\nNuevo email: nuevo@email.com"
    validations:
      required: false

  - type: textarea
    id: detalle_incentivos
    attributes:
      label: "💰 Cambios en Incentivos"
      description: "Si cambiaron los incentivos, describe los cambios"
      placeholder: "Antes: Puntos canjeables\nAhora: Descuentos del 10% en productos\nO: Ya no ofrecen incentivos"
    validations:
      required: false

  - type: textarea
    id: detalle_otro_cambio
    attributes:
      label: "📝 Otro Cambio"
      description: "Si seleccionaste 'Otro cambio', describe qué cambió"
      placeholder: "Describe el cambio que observaste..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 📝 Información Adicional

  - type: textarea
    id: informacion_adicional
    attributes:
      label: "📋 Información Adicional"
      description: "Cualquier información adicional que consideres relevante"
      placeholder: "Comentarios adicionales, observaciones, etc."
    validations:
      required: false

  - type: input
    id: fecha_visita
    attributes:
      label: "📅 Fecha de Verificación"
      description: "¿Cuándo visitaste o verificaste esta información?"
      placeholder: "Enero 2025"
    validations:
      required: true

  - type: checkboxes
    id: verificacion
    attributes:
      label: "✅ Verificación"
      description: "Por favor confirma lo siguiente"
      options:
        - label: "He verificado que esta información es precisa según mi conocimiento."
          required: true
        - label: "Confirmo que este punto YA EXISTE en el directorio actual."
          required: true
        - label: "He usado el nombre exacto como aparece en el directorio."
          required: true

  - type: checkboxes
    id: codigo_conducta
    attributes:
      label: "¿Has Leído Nuestro Código de Conducta?"
      description: "Por favor confirma que has leído y entendido nuestro [Código de Conducta](https://github.com/Aqui-Reciclo-Panama/.github/blob/main/CODE_OF_CONDUCT.md)."
      options:
        - label: "Sí, he leído y acepto el Código de Conducta."
          required: true
