name: "🔄 Actualizar Punto Existente"
description: "Actualizar información de un punto de reciclaje que ya está en nuestro directorio."
title: "🔄 Actualizar: [Nombre del Punto]"
labels: ["actualizar-punto", "punto-reciclaje"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🔄 Actualizar Punto de Reciclaje Existente

        **¿Encontraste cambios en un punto que ya está registrado?** ¡Gracias por ayudarnos a mantener la información actualizada!

        **⚠️ IMPORTANTE:** Para actualizar correctamente, necesitas el enlace exacto del punto.

        **Cómo obtener el enlace:**
        1. Encuentra el punto de reciclaje
        3. Entra a la pestaña "Detalles" del punto
        4. Copia el enlace completo de esa página

        **¿Es un punto nuevo que no existe?** 
        Usa este formulario: [Reportar Nuevo Punto](https://github.com/Aqui-Reciclo-Panama/.github/issues/new?template=new-center.yml)

        ---

  - type: dropdown
    id: fuente_informacion
    attributes:
      label: "🔍 ¿Cómo obtuviste esta información?"
      options:
        - ""
        - "Trabajo/soy dueño del punto de reciclaje"
        - "Visité el punto personalmente"
        - "Lo vi en redes sociales/internet"
        - "Otro"
    validations:
      required: true

  - type: input
    id: link_punto
    attributes:
      label: "🔗 Enlace del Punto de Reciclaje"
      description: "Ve a aquireciclo.org, busca el punto, entra a la pestaña 'Detalles', y copia el enlace completo"
      placeholder: "https://aquireciclo.org/punto/123-nombre-del-punto"
    validations:
      required: true

  - type: textarea
    id: ubicacion_confirmacion
    attributes:
      label: "🗺️ Ubicación (para confirmar que es el punto correcto)"
      description: "Provincia y dirección aproximada"
      placeholder: "Ej: Panamá, Calle 50, cerca del Metro Mall"
    validations:
      required: true

  - type: checkboxes
    id: que_cambio
    attributes:
      label: "🔍 ¿Qué ha cambiado?"
      description: "Selecciona todos los cambios que observaste"
      options:
        - label: "🕐 Horarios de atención"
        - label: "🚫 El punto cerró permanentemente"
        - label: "⏸️ Cerrado temporalmente"
        - label: "➕ Ahora acepta materiales adicionales"
        - label: "➖ Ya no acepta algunos materiales"
        - label: "📞 Información de contacto (teléfono/email)"
        - label: "💰 Incentivos (cambió o ya no ofrece)"
        - label: "📝 Otro cambio"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 📝 Describe los Cambios
        **Solo completa las secciones que apliquen según lo que seleccionaste arriba**

  - type: textarea
    id: nuevos_horarios
    attributes:
      label: "🕐 Nuevos Horarios"
      placeholder: "Ej: Lun-Vie: 8AM-5PM, Sáb: 8AM-12PM, Dom: Cerrado"
    validations:
      required: false

  - type: textarea
    id: cierre_detalles
    attributes:
      label: "🚫 Detalles del Cierre"
      description: "Si cerró permanente o temporalmente"
      placeholder: "Ej: Cerró en enero 2025, el local está vacío / Cerrado por renovaciones hasta marzo 2025"
    validations:
      required: false

  - type: textarea
    id: materiales_cambios
    attributes:
      label: "♻️ Cambios en Materiales"
      description: "Materiales nuevos que acepta (+) o que ya no acepta (-)"
      placeholder: "Ej: + Ahora acepta: pilas, aceite de cocina\n- Ya no acepta: vidrio, textiles"
    validations:
      required: false

  - type: textarea
    id: contacto_nuevo
    attributes:
      label: "📞 Nueva Información de Contacto"
      placeholder: "Nuevo teléfono: +507 123-4567\nNuevo email: contacto@punto.com"
    validations:
      required: false

  - type: textarea
    id: incentivos_cambios
    attributes:
      label: "💰 Cambios en Incentivos"
      placeholder: "Ej: Ya no dan descuentos / Ahora dan B/.0.10 por libra de plástico"
    validations:
      required: false

  - type: textarea
    id: otros_cambios
    attributes:
      label: "📝 Otros Cambios"
      placeholder: "Describe cualquier otro cambio que observaste"
    validations:
      required: false

  - type: input
    id: fecha_verificacion
    attributes:
      label: "📅 ¿Cuándo verificaste esta información?"
      placeholder: "Ej: Enero 2025, Esta semana"
    validations:
      required: true

  - type: textarea
    id: comentarios_adicionales
    attributes:
      label: "💬 Comentarios Adicionales (Opcional)"
      placeholder: "Cualquier información extra que consideres importante"
    validations:
      required: false

  - type: checkboxes
    id: verificacion
    attributes:
      label: "✅ Confirmación"
      options:
        - label: "Copié el enlace desde la pestaña 'Detalles' del punto"
          required: true
        - label: "Esta información es precisa según mi conocimiento"
          required: true
